# Copyright (c) 2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.

# SPDX-FileCopyrightText: NVIDIA CORPORATION & AFFILIATES
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_stages:
  - merge-commit
  - commit
  - post-rewrite

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-merge-conflict
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args: ['--fix=lf']
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: detect-private-key
  - id: check-added-large-files
  - id: check-case-conflict
  - id: destroyed-symlinks
  - id: check-yaml
    exclude: '.clang-format'

- repo: https://github.com/detailyang/pre-commit-shell
  rev: 1.0.5
  hooks:
  - id: shell-lint
    args: ['-x', '--severity=warning']

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v14.0.6
  hooks:
  - id: clang-format

- repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
  rev: v0.1.0
  hooks:
  - id: dockerfilelint

- repo: local
  hooks:
  - id: copyright_check
    name: 'check copyright message'
    language: system
    types: ['file', 'text']
    exclude_types: ['markdown']
    entry: ./lint/copyright_check.sh
  - id: lfs_check
    name: 'check LFS objects'
    language: system
    entry: ./lint/lfs_check.sh
    require_serial: true

- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.0.0
  hooks:
  - id: commitlint
    stages: [commit-msg]
    args: ['--config','lint/commitlint.config.js']
    additional_dependencies: ['@commitlint/config-conventional']
